# Generated by Django 3.0.2 on 2020-01-28 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import votes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=votes.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.UUIDField(default=votes.models.hex_uuid, editable=False)),
                ('vote_type', models.IntegerField(choices=[(0, 'neutral'), (1, 'up'), (2, 'down')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
