# Generated by Django 3.0.2 on 2020-01-21 18:05

from django.db import migrations, models
import django.db.models.deletion
import specials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deal_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('deal_url', models.URLField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('front_page', models.BooleanField(default=False)),
                ('src', models.ImageField(upload_to='images/items')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='specials.Category')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='specials.Store')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
