# Generated by Django 2.2.5 on 2019-09-25 03:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import specials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sub_category_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specials.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.UUIDField(default=specials.models.hex_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('original_price', models.PositiveIntegerField()),
                ('offer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('new_price', models.PositiveIntegerField()),
                ('offer_expired', models.BooleanField(default=False)),
                ('front_page', models.BooleanField(default=False)),
                ('offer_expiry_date', models.DateField()),
                ('src', models.ImageField(upload_to='images/items')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specials.Store')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specials.SubCategory')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
