# Generated by Django 3.0.2 on 2020-02-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
