# Generated by Django 2.2.5 on 2019-09-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='offer_expiry_date',
            field=models.DateField(),
        ),
    ]
