# Generated by Django 2.2.6 on 2019-10-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0003_auto_20191029_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='specials.Store'),
        ),
    ]
