# Generated by Django 3.0.2 on 2020-02-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0003_auto_20200201_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
