# Generated by Django 2.2.6 on 2019-10-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0004_auto_20191030_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
