# Generated by Django 3.0.2 on 2020-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0004_auto_20200201_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
