# Generated by Django 3.0.2 on 2020-02-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0005_auto_20200203_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deal_url',
            field=models.URLField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
